### ISSUE TITLE
LOD Life Cycle Action - Execute Custom Script

### ISSUE THREAD

**Issue by dadlMs** [LearnOnDemandSystems/docs#834]
**Description of proposed changes**: 
Please detail how to specify targets within script. Doc says "Scripts can be executed against a custom target" but does not specify how to identify those targets. 

Doc points to a link:

For more information about the available languages, see our [Lab on Demand Scripting documentation](https://github.com/LearnOnDemandSystems/docs/blob/master/lod/scripting-home.md).

But this link only has a few examples and none of them explain how to specify a "custom target"

I would like to use this to run initial lab setup actions, and keep them contained inside a single script instead of having many lifecycle actions executed against single targets. If this is not possible or not the intended design, then I would suggest to clarify the docs.

**Link to the document**: 
https://github.com/LearnOnDemandSystems/docs/blob/master/lod/life-cycle-actions.md

**Screenshots (optional)**:

**Comment by paulieguk** [comment]
A Custom Target would be something outside of the LOD Platform.  So for example an Custom Target might be a Web Apps API.  Some examples I have used for an LCA would be:

Set the Action to: Execute Custom Script
Set the Language to: PowerShell
Then create a script to access an external API.  I have used one to enable Dynamic DNS registration with GoDaddy, or to register the user launching the lab with a Gamification scoreboard to produce a leader board as users complete the lab.  This link is my GoDaddy example: https://github.com/paulieguk/Skillable-API-PS-Scripts/blob/main/003%20Update%20Public%20DNS%20via%20API

Regards,
Paul

Paul Gregory MCSE, MCT | Solutions Engineer
+44 7970-155456 (UK | UTC)
***@***.******@***.***>
https://skillable.com | LinkedIn <https://www.linkedin.com/in/paullgregory/>   | Twitter<https://twitter.com/paullgregory>

***@***.***

From: dadlMs ***@***.***>
Sent: 30 June 2022 17:22
To: LearnOnDemandSystems/docs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [LearnOnDemandSystems/docs] LOD Life Cycle Action - Execute Custom Script (Issue #834)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe. Also, please think before you reply-all to external recipients.

Description of proposed changes:
Please detail how to specify targets within script. Doc says "Scripts can be executed against a custom target" but does not specify how to identify those targets.

Doc points to a link:

For more information about the available languages, see our Lab on Demand Scripting documentation<https://github.com/LearnOnDemandSystems/docs/blob/master/lod/scripting-home.md>.

But this link only has a few examples and none of them explain how to specify a "custom target"

I would like to use this to run initial lab setup actions, and keep them contained inside a single script instead of having many lifecycle actions executed against single targets. If this is not possible or not the intended design, then I would suggest to clarify the docs.

Link to the document:
https://github.com/LearnOnDemandSystems/docs/blob/master/lod/life-cycle-actions.md

Screenshots (optional):

**Comment by dadlMs** [comment]
@paulieguk Thank you for the prompt reply. I feel that I understand the process more now.
