### ISSUE TITLE
i can not sign in because my keyborad is not accept cant put in @

### ISSUE THREAD

**Issue by Artur-RB** [LearnOnDemandSystems/docs#922]
**Description of proposed changes**: 
Enter description here

**Link to the document**: 
Enter link here

**Screenshots (optional)**:

**Comment by Artur-RB** [comment]
what can i do when my keyboard not working at all cant write @ by an email

**Comment by paulieguk** [comment]
So the issue is your keyboard is working but you cannot type the @ Symbol.  OK this is normally due to keyboard localization issues between your local machine and the language the VM is in.  Generally you will find labs are built in US English and if you have a non us English keyboard you normally find the @ and the “ have been swapped on the keyboard.  If that does not resolve you issue, at the top left you will see a lightning bolt, behind that menu you will find the virtual keyboard and that will let you enter an @ symbol too.

Any further issues of lab usage please contact Skillable support (https://www.skillable.com/customer-support) as this is more related to documentation issues rather than customer support issues.

Regards,
Paul

Paul Gregory MCSE, MCT | Solutions Engineer
+44 7970-155456 (UK | UTC)
***@***.******@***.***>
https://skillable.com | LinkedIn <https://www.linkedin.com/in/paullgregory/>   | Twitter<https://twitter.com/paullgregory>

***@***.***

**Comment by Artur-RB** [comment]
no doesnt work, got the keyboard and can put in the email
but with the password doesnt work
can i do the lab offline 
where do i get the sheets

**Comment by paulieguk** [comment]
As stated this is not customer support for lab issues.  Please contact our customer support as per the last message how can help you.
Regards,
Paul

Paul Gregory MCSE, MCT | Solutions Engineer
+44 7970-155456 (UK | UTC)
***@***.******@***.***>
https://skillable.com | LinkedIn <https://www.linkedin.com/in/paullgregory/>   | Twitter<https://twitter.com/paullgregory>

***@***.***
